### ISSUE TITLE
Pollard-rho lambda (pollard-rho kangaroo)

### ISSUE THREAD

**Issue by username1565** [qubd/mini_ecdsa#5]
Is there any implementation for [Pollard-rho lambda algorithm (kangaroo algorithm)](https://crypto.stackexchange.com/a/48051)?

This algo can be parallelized, and workint in range with O(sqrt(a-b)),
but I cann't understand how this works, and how to modify this to solve ECDLP...
If you have free time, you can implement this just for fun

**Comment by username1565** [comment]
Look at this: https://eprint.iacr.org/2013/596.pdf https://catalog.lib.kyushu-u.ac.jp/opac_download_md/1434304/p145.pdf
Can you programming this?

**Comment by qubd** [comment]
Sorry, but I don't intend to do anything more with this package in the future. My only goal was to implement ECDSA from scratch to make sure I understood some of the technical details of ECC.

I've heard of Pollard's lambda algorithm (a.k.a kangaroo algorithm). It has a lot in common with the rho algorithm, which is implemented here. Have at it!

I didn't know there was a claimed subexponential time method for fields of characteristic two, but checking out https://safecurves.cr.yp.to/field.html, it's referenced there too. I guess this is why prime characteristic fields are used in practice.

**Comment by username1565** [comment]
Ok.
I think you just can add the functions to half point in finite field,
divide point to k (by subtraction- and subtraction and halving)
and function to subtract point from another point.
Q(x, y) - P(x, y) = Q(x, y) + P(x, -y)
Q(x, y) / 2 = Q(x, y) * mult_inv(2, n)
Q(x, y) / k = Q(x, y) * mult_inv(k, n); or subtract-halving algo.
Just need to test this all.

Also, if there is possible to generate semigroup of the points of elliptic curve, and if there is possible to check is the point in the semigroup or not, I think then is possible to solve ECDLP faster.
I have some ideas about it.

**Comment by dem10** [comment]
Yes, parallelization is a good idea. It’s also a birthday paradox that seems to work if we know Q. I heard that the Brent method is faster than Floyd by 30-40 percent .

**Comment by dem10** [comment]
> Ok.
> I think you just can add the functions to half point in finite field,
> divide point to k (by subtraction- and subtraction and halving)
> and function to subtract point from another point.
> Q(x, y) - P(x, y) = Q(x, y) + P(x, -y%p)
> Q(x, y) / 2 = Q(x, y) * mult_inv(2, n)
> Q(x, y) / k = Q(x, y) * mult_inv(k, n); or subtract-halving algo.
> Just need to programming this and then test this all, after comparing with results of addition and multiple functions.
> 
> Also, if there is possible to generate semigroup of the points of elliptic curve, and if there is possible to check is the point in the semigroup or not, I think then is possible to solve ECDLP faster.
> I have some ideas about it.
> 
> 1. Point Q = kP, in the group of poins, generated from generator point P,
>    there is in first semigroup of group with points, generated from generator point 2P,
>    when k is even, and in the second semigroup 2P, when k is odd.
> 2. If Q = kP in first semigroup 2P, then k is odd, if Q = kP in second semigroup 2P - then k is even.
> 3. If k is odd - (kP-P)/2, if k is even kP/2
> 4. Extract bits of k from Q = kP from sequence of halfing-subtraction-halving points.
>    =)

Yes, parallelization is a good idea. It’s also a birthday paradox that seems to work if we know Q. I heard that the Brent method is faster than Floyd by 30-40 percent .This concerns Pollard_rho. But I think it will be a completely different tool and implementation on C ++, but the developer has no desire to continue working in this direction. So we smoke in silence.

**Comment by username1565** [comment]
Nothing prevents to make the fork of the source code and make changes to the code, with adding some functions to it. Just need to be able to do it correctly, according the python syntax.

**Comment by dem10** [comment]
> Nothing prevents to make the fork of the source code and make changes to the code, with adding some functions to it. Just need to be able to do it correctly, according the python syntax.

Python is not the fastest option. If I could, I would not have written here, but would have already created my own tool. There is another developer who wanted to create such a tool, but unfortunately he doesn’t have free time.

**Comment by username1565** [comment]
I think to solve the ECDLP need to look for mathematical and algebraic methods. Maybe on elliptic curve can be realized many operations, like that two (division and subtraction), and maybe this operations can help to solve ECDLP. Also, addition and double working with the lines, and angle of this lines. Maybe some lines or formulas can help to solve this without brute-force. Just we didn't know about it and how to do it, we just have formula for addition points.

**Comment by username1565** [comment]
More ECDLP methods - [available here](https://www.researchgate.net/file.PostFileLoader.html?id=5583faed6225ff040e8b458b&assetKey=AS%3A273804985602059%401442291603545):

**Comment by username1565** [comment]
Hm... Is it possible to using [general number field sieve, GNFS](https://en.wikipedia.org/wiki/General_number_field_sieve) to [solve ECDLP](https://en.wikipedia.org/wiki/Discrete_logarithm_records#Integers modulo p)?
Elliptic curve dots have indexes, where each index is in the multiplicative group of integers modulo n, and n is e prime number for finite field.
If GNFS can be used to solve ECDLP, this may be subexponential algorithm.

**Comment by Saadinr** [comment]
Pollard Rho kangaroo https://twitter.com/1Bursh/status/1155383702689656832

**Comment by username1565** [comment]
@Saadinr, link not working.

**Comment by Saadinr** [comment]
sory
https://twitter.com/Burshs1/status/1155519842566451200

**Comment by username1565** [comment]
@Saadinr, LOL! Just copy & paste from here: https://crypto.stackexchange.com/a/48051
xD

**Comment by su314ka** [comment]
> sory
> https://twitter.com/Burshs1/status/1155519842566451200

100% SCAM. Don`t lose your money.
