### ISSUE TITLE
Respond No Result in command..

### ISSUE THREAD

**Issue by ashraful1980** [qubd/mini_ecdsa#9]
Dear Sir,
Have a nice day and hope you are doing well.

I have checked all data everything is compile smoothly; but once i have command in python3 mini_ecdsa.py it is not found any result. Could you please advice how to use your python code....

![image](https://user-images.githubusercontent.com/52574658/123472446-00bf5e00-d619-11eb-93c1-2cac953bc69f.png)

**Comment by qubd** [comment]
Seems like it was working fine from your screenshot. When you run the command
```
python3 mini_ecdsa.py
```
python will execute the file as if it's a script, which will produce no output. 

The code is this repo is a python module which you can use interactively, or import for use in another project. For more information see [this link](https://realpython.com/lessons/scripts-modules-packages-and-libraries/).
